---
- name: Install PostgreSQL repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Install PostgreSQL client
  yum:
    name: postgresql{{ pg_version }}
    state: present

- name: Add EPEL repo
  yum:
    name: epel-release
    state: present

- name: Install barman
  yum:
    name: barman
    state: present

- name: Copy .pgpass for {{ barman_login }}
  template:
    src: barman_pgpass.j2
    dest: /var/lib/barman/.pgpass
    owner: barman
    group: barman
    mode: 0600

- name: Copy barman.conf to backup server
  template:
    src: barman.conf.j2
    dest: /etc/barman.conf

- name: Copy pg.conf to backup server
  template:
    src: pg.conf.j2
    dest: /etc/barman.d/pg.conf

- name: Check if continuous archiving is on and properly working
  become_user: barman
  shell: "barman check pg | grep 'WAL archive: FAILED' | cat"
  register: wal_archive

# For some reason it fails on the first run
- name: Force PostgreSQL to switch WAL file and trigger the archiving process
  become_user: barman
  command: barman switch-wal --force --archive pg
  register: result
  until: result is not failed
  retries: 3
  delay: 5
  when: wal_archive.stdout != ""

### Allow connect from backup server to master server via SSH ###

- name: Create directory for SSH keypair
  file:
    path: /var/lib/barman/.ssh
    state: directory
    owner: barman
    group: barman
    mode: 0700

- name: Generate SSH key for barman user
  become_user: barman
  openssh_keypair:
    path: ~/.ssh/id_rsa
  register: barman_pub_key

- name: Set authorized key for postgres user
  authorized_key:
    user: postgres
    state: present
    key: "{{ barman_pub_key.public_key }}"
  delegate_to: master
