---
# - name: Generate SSH keys for root
#   user:
#     name: root
#     generate_ssh_key: yes

# - name: Create SSH config
#   copy:
#     content: StrictHostKeyChecking no
#     dest: /root/.ssh/config

- name: Create a directory for Docker Compose file
  file:
    path: "{{ project_dir }}-local"
    state: directory

- name: Copy files to "{{ project_dir }}-local"
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{ project_dir }}-local/"

- name: Copy env files to "{{ project_dir }}-local"
  template:
    src: "{{ item }}"
    dest: "{{ project_dir }}-local/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_fileglob:
    - "{{ role_path }}/templates/*.j2"

- name: Run Nextcloud
  docker_compose:
    project_src: "{{ project_dir }}-local"
