---
- name: Create a trusted storage pool
  gluster_peer:
    state: present
    nodes:
      - 10.10.10.11
      - 10.10.10.12
      - 10.10.10.13

- name: Create directory for gluster volume
  file:
    path: /opt/gluster-volume-nextcloud
    state: directory

- name: Create gluster volume
  gluster_volume:
    state: present
    name: nextcloud-gfs
    bricks: /opt/gluster-volume-nextcloud
    replicas: 3
    arbiters: 1
    force: yes
    cluster:
      - 10.10.10.11
      - 10.10.10.12
      - 10.10.10.13
  run_once: true
 
- name: Start gluster volume if it's stopped
  gluster_volume:
    state: started
    name: nextcloud-gfs
  run_once: true

- name: Create directory for mount gluster volume
  file:
    path: /opt/nextcloud
    state: directory

- name: Mount GlusterFS
  mount:
    path: /opt/nextcloud
    src: localhost:/nextcloud-gfs
    fstype: glusterfs
    opts: defaults,_netdev
    state: mounted

# backupvolfile-server=localhost
