---
- name: Create a trusted storage pool
  gluster_peer:
    state: present
    nodes:
      - 10.10.10.11
      - 10.10.10.12
      - 10.10.10.13

- name: Create directory for gluster volume
  file:
    path: /opt/gluster-volume-nextcloud
    state: directory

- name: Create gluster volume
  gluster_volume:
    state: present
    name: nextcloud-gfs
    bricks: /opt/gluster-volume-nextcloud
    replicas: 2
    arbiters: 1
    force: yes
    cluster:
      - 10.10.10.11
      - 10.10.10.12
      - 10.10.10.13
  run_once: true
 
- name: Start gluster volume if it's stopped
  gluster_volume:
    state: started
    name: nextcloud-gfs
  run_once: true

# - name: Tune GlusterFS
#   command: gluster volume set nextcloud-gfs {{ item }}
#   with_items:
#     - performance.write-behind on
#     - nfs.disable on
#     - cluster.lookup-optimize off
#     - performance.stat-prefetch off
#     - server.allow-insecure on
#     - storage.batch-fsync-delay-usec 0
#     - performance.client-io-threads off
#     - network.frame-timeout 60
#     - performance.quick-read on
#     - performance.flush-behind off
#     - performance.io-cache off
#     - performance.read-ahead off
#     - performance.cache-size 0
#     - performance.io-thread-count 64
#     - performance.high-prio-threads 64
#     - performance.normal-prio-threads 64
#     - network.ping-timeout 5
#     - server.event-threads 16
#     - client.event-threads 16

- name: Create directory for mount gluster volume
  file:
    path: /opt/nextcloud
    state: directory

- name: Mount GlusterFS
  mount:
    path: /opt/nextcloud
    src: localhost:/nextcloud-gfs
    fstype: glusterfs
    opts: defaults,_netdev
    state: mounted

# backupvolfile-server=localhost
