---
- name: Create user {{ barman_login }} in PostgreSQL
  become_user: postgres  
  postgresql_user:
    name: "{{ barman_login }}"
    password: "{{ barman_password }}"
    role_attr_flags: SUPERUSER
    expires: infinity
  no_log: yes

- name: Create {{ streaming_barman_login }} user
  become_user: postgres  
  postgresql_user:
    name: "{{ streaming_barman_login }}"
    password: "{{ streaming_barman_password }}"
    role_attr_flags: REPLICATION
    expires: infinity
  no_log: yes

- name: Allow {{ streaming_barman_login }} connect to master
  lineinfile:
    path: "{{ db_path }}/pg_hba.conf"
    line: host    replication     {{ streaming_barman_login }}     {{ backup_host_ip }}/32            md5
  notify:
    - Restart postgresql

- name: Copy postgresql.conf with settings for replication
  copy:
    src: postgresql.conf
    dest: "{{ db_path }}/postgresql.conf"
  notify:
    - Restart postgresql
