---
- name: Check if NFS Utils is intalled
  yum:
    name: nfs-utils
    state: present

- name: Check if rpcbind is running
  systemd:
    name: rpcbind
    state: started
    enabled: yes

# - name: Create folder to mount
#   file:
#     path: "{{ mnt_path }}"
#     state: directory

- name: Mount shared folder
  mount:
    path: "{{ mnt_path }}"
    src: "{{ server_ip }}:{{ share_path }}"
    fstype: nfs
    opts: hard,intr,_netdev,noauto,x-systemd.automount
    state: mounted
