---
- name: Create a directory for Docker Compose file
  file:
    path: "{{ project_dir }}"
    state: directory

- name: Copy docker-compose.yml to {{ project_dir }}
  copy:
    src: docker-compose.yml
    dest: "{{ project_dir }}/docker-compose.yml"

- name: Run Redis
  docker_compose:
    project_src: "{{ project_dir }}"
