version: '3'

services:
  app:
    container_name: app-server
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
      # - ./custom_apps:/var/www/html/custom_apps
      # - ./config:/var/www/html/config
      # - ./data:/var/www/html/data
    env_file:
      - db.env
      - app.env
      - app_cred.env

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    volumes:
      - /opt/document_data:/var/www/onlyoffice/Data
      - /opt/document_log:/var/log/onlyoffice

  nginx:
    container_name: nginx-server
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud:/var/www/html:ro
    depends_on:
      - app
      - onlyoffice-document-server
