version: '3'

services:
  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
      # - ./custom_apps:/var/www/html/custom_apps
      # - ./config:/var/www/html/config
      # - ./data:/var/www/html/data
    env_file:
      - db.env
      - app.env
      - app_cred.env

  web:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud:/var/www/html:ro
    depends_on:
      - app
