---
- name: Create a directory for Docker Compose file
  file:
    path: "{{ project_dir }}"
    state: directory

- name: Copy docker-compose.yml to {{ project_dir }}
  copy:
    src: docker-compose.yml
    dest: "{{ project_dir }}/docker-compose.yml"

- name: Copy env file to {{ project_dir }}
  template:
    src: db.env.j2
    dest: "{{ project_dir }}/db.env"

- name: Run PostgreSQL
  docker_compose:
    project_src: "{{ project_dir }}"
